### ISSUE TITLE
Not working with Compute Module 3 :(

### ISSUE THREAD

**Issue by Silvia-t** [nebrius/raspi-i2c#14]
Hi guys,

I didn't read about any limitations when using the raspi-i2c with a compute module, but when trying to run a test program on CM3:

`Unknown board revision a220a0, assuming Raspberry Pi Zerp/2/3 pinout. Unless you are running a compute module or very old RPi this should work fine. Please report this board revision in a GitHub issue at https://github.com/nebrius/raspi-board.`

Is there any way in which the GPIO to be used for i2c could be user-defined? 

Thanks.

**Comment by nebrius** [comment]
That warning is expected, as I've never added support for computer modules.

We can't use any GPIO for I2C because of the way I2C works. It doesn't work by setting pins high or low, it works by setting pins low or "high impedance," using what's called an open-drain transistor configuration. As such, you need hardware support to do I2C.

I've never used a compute module before, so I don't know what it exposes. I would assume that the compute module routes the hardware I2C pins to it's external pins though. I'll add though that the Raspi.js suite doesn't support the compute module officially (I should add this to the list of requirements). In the case of I2C though, it should mostly work though.

Do you need to run any other modules from Raspi.js on your compute module? If not, I'd recommend using [i2c-bus](https://www.npmjs.com/package/i2c-bus) directly, which is the module I use to get I2C support.

P.S. I'd like to request that you don't use "guys" to describe us as a group of collaborators. We're not all guys, and culturally as a project we strive to use gender neutral language.

**Comment by Silvia-t** [comment]
Hi @nebrius,

Thanks for your reply.

i2c works on the compute module (or, at least, in the dev kit) like on the RPi; it has 4 GPIO pins which can double up as i2c (buses 0 and 1). I've connected SCL and SDA to GPIO 2 and 3 for bus 1, so except for the pin numbers, it's all the same as on the RPi.

Yes, I think specifying that this module doesn't support CM is a good idea :)

No, I don't need any other modules from raspi.js -- I didn't know the i2c part was based on i2c-bus, which I have also installed (but I was looking for alternatives, as I am struggling to see how to address a specific register.). 


PS. Sorry if I offended anyone using the word "guys", it was meant as a collective name rather than men-only! It wasn't my intention to exclude any other groups. Next time I'll just keep it to "Hi" :)

**Comment by nebrius** [comment]
@Silvia-t the raspi-i2c API is a very thin shim on top of i2c-bus, and the APIs are really similar. In the I2C Bus documentation, registers are referred to as "commands," which I could see being confusing if you were looking for something titled "register." Hope that helps!

**Comment by Silvia-t** [comment]
Thanks for the info @nebrius :)

**Comment by nebrius** [comment]
I'm going to close this issue now, but feel free to reopen if you have anymore questions. FYI I did add a note in the project requirements that the compute module is not supported.
